### ISSUE TITLE
Warning, your Odoo database manager is not protected

### ISSUE THREAD

**Issue by open7c** [odoo/docker#167]
After each update of the Docker Container, the Database Manager isn't protected anymore.

What to do to persist that?

**Comment by thomas15v** [comment]
Override the odoo.conf.

`docker .... -v ./odoo.conf:/etc/odoo/odoo.conf`

**Comment by open7c** [comment]
thx, is working...

**Comment by greaber** [comment]
I don't think this issue should have been closed.  The way of running the system suggested in the docs is massively insecure.  At least they should be changed.  But also maybe odoo itself should work differently.  Normally .conf files are edited by humans and not expected to contain application state.  (And really Odoo just shouldn't allow not having a password on the database manager once they system is initialized.)

**Comment by thomas15v** [comment]
I completely agree, I actually would prefer if a new password is generated when the page is visited and asks to look at the console since it has written it there. After an hour of inactivity the admin password has to be discarded. Next time you visit you get a new password. But this isn't something that can be fixed in the docker container tho.
