### ISSUE TITLE
sudo: command not found

### ISSUE THREAD

**Issue by ybouhjira** [odoo/docker#21]
I can't run the scaffolding command in `/mnt/extra-addons/` because it belongs to `root` and there is not `sudo` command.

```
odoo@759e55619372:/mnt/extra-addons$ sudo odoo.py scaffold openacademy .
bash: sudo: command not found
```

**Comment by mlaitinen** [comment]
What if you add `RUN chown odoo /mnt/extra-addons` to the Dockerfile and try scaffolding without sudo? If that works, you could make a pull request.

**Comment by anandumdas** [comment]
The error happens because the binary you are trying to call from command line is only part of the current user's PATH variable, but not a part of  root user's PATH.

You can verify this by locating the path of the binary you are trying to access. In my case I was trying to call "bettercap-ng". So I ran,

`$ which bettercap-ng`

`output: /home/user/work/bin/bettercap`

I checked whether this location is part of my root user's PATH.

`$ sudo env | grep ^PATH`

output: `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

So sudo cannot find the binary that I am trying to call from commandline. Hence returns the error command not found. 

You can direct sudo to use the current user's PATH when calling a binary like below.

`$ sudo -E env "PATH=$PATH" [command] [arguments]`

In fact, one can make an alias out of it:

`$ alias mysudo='sudo -E env "PATH=$PATH"'`

It's also possible to name the alias itself sudo, replacing the original sudo.

Please refer to [this video][1] for step by step solution


  [1]: https://youtu.be/nTLuTZqQbNI
