### ISSUE TITLE
wkhtmltopdf

### ISSUE THREAD

**Issue by AhmadZarour93** [odoo/docker#220]
Dockerfile downloads 0.12.4 however in the documentation recommended version is 0.12.1

**Comment by igallart** [comment]
I think the same, what it version is correct?

**Comment by odony** [comment]
0.12.4 was not available for Debian 9, which is why we used 0.12.4.

There is now an official build of 0.12.5 for [Stretch (0.12.5.1)](https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb), so we are going to try it and update the Dockerfiles to use it.
We have already updated the [wiki page](https://github.com/odoo/odoo/wiki/Wkhtmltopdf) to explain that 0.12.5 is now recommended for Odoo 10.0 and later. 0.12.1.3 is still OK for platforms who have it.

cc @d-fence

**Comment by igallart** [comment]
@odony, in this documentation, it should to be changed also (10,11,12,) https://www.odoo.com/documentation/11.0/setup/install.html

**Comment by d-fence** [comment]
I'm working on docker update.

**Comment by odony** [comment]
The doc of 10.0 [has been updated](https://github.com/odoo/odoo/commit/3b85900fafc9469dca6e7c01fca6dac4f55d20f5), and the changes will be forward-ported to later versions soon. They should be visible on our website tomorrow after the next rebuild.

**Comment by d-fence** [comment]
@odony Thanks, docker images are almost ready.

**Comment by d-fence** [comment]
Pull request to update images is a WIP :
https://github.com/docker-library/official-images/pull/5103
