### ISSUE TITLE
Typo in Dockerfile (11, 12 and 13)

### ISSUE THREAD

**Issue by fractalf** [odoo/docker#287]
Next time you guys update the Dockerfile, please fix this simple typo:

The *etc* path should have a path starting from root ie */etc*

So these

https://github.com/odoo/docker/blob/596a7cabc07dd3b1d18b6c2832cace7328e36969/11.0/Dockerfile#L39

https://github.com/odoo/docker/blob/596a7cabc07dd3b1d18b6c2832cace7328e36969/12.0/Dockerfile#L39

https://github.com/odoo/docker/blob/596a7cabc07dd3b1d18b6c2832cace7328e36969/13.0/Dockerfile#L37

should be replaced by 
```
        echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
```

**Comment by alorence** [comment]
I was thinking about the reason this didn"t cause truble for 10 months now. I saw that none of Odoo Docker image contains `WORDKIR`, and sources images (Debian in various flavor) doesn't use it ether:

https://github.com/debuerreotype/docker-debian-artifacts/blob/dist-amd64/jessie/Dockerfile
https://github.com/debuerreotype/docker-debian-artifacts/blob/dist-amd64/buster/slim/Dockerfile
https://github.com/debuerreotype/docker-debian-artifacts/blob/dist-amd64/stretch/slim/Dockerfile

So apparently, the default `WORKDIR` is `/`, that's why it works as expected. But It should definitely be fixed
