### ISSUE TITLE
Add latest release image

### ISSUE THREAD

**Issue by Sirfanas** [odoo/docker#293]
Hi,
I think it can be good to have more Docker update,
Maybe a daily release, to match with the odoo.deb release
Cause actually we are on November 6 release, whose actually have 2 month, and a lot of fix are available
So I have to manually rebuild the image, it took me time and I'm sure I'm not the only one who have this problem

Thank's
Have a good day !

**Comment by codeagencybe** [comment]
I agree, the docker releases are so much slower than the regular ones. 
Important bugfixes keep waiting for weeks or even months because of this. 

A new Docker image every day would be nice but I would be happy if they update at least every 1~2 weeks on a fix schedule. At least you can count on a new update to be available within the next 1-2 weeks and schedule ahead same.

**Comment by d-fence** [comment]
Done here https://github.com/docker-library/official-images/commit/0e0bac8e928c5d35e4633ac83d7f752f059c9209
