### ISSUE TITLE
Odoo version stucked to 20141231

### ISSUE THREAD

**Issue by theyoux** [odoo/docker#3]
Hi,
I wonder why the odoo version to be installed is hardcoded to 20141231.
Can we change it with "latest"?

**Comment by aab-odoo** [comment]
Hello,

Docker's philosophy is to pin versions so that it can produce repeatable builds. Indeed, as building a docker image may or not use the cache, using latest you would have no control over the actual version you are using.

Anyway, you can still enter your Odoo container and update Odoo to the latest version with 
apt-get update && apt-get upgrade.

We also plan to upgrade the Odoo image on a regular basis.

**Comment by theyoux** [comment]
Thanks for the explanation.
I close that ticket.
