### ISSUE TITLE
Impossible to scaffold new addon

### ISSUE THREAD

**Issue by Rustem** [odoo/docker#38]
Hi I am using docker-compose. Installation process and server running is going quite well, but when I am trying to add new addon with a command `docker-compose run odoo odoo.py scaffold newmodule /mnt/addons`, odoo throws Permission Denied. I know that's because `odoo` user has no enough permissions to /var/lib/odoo. What is the good workaround ? I suspect we should either add permissions while building image from Dockerfile with chown or add odoo user in sudoers file. Could you extend your readme on how to launch different odoo.py commands behind docker. May be

**Comment by sle-odoo** [comment]
Hi,
I cannot reproduce your issue. It seems that the permissions are correct. 

```
docker run -p 8069:8069 --name odoo --link db:db -t odoo /usr/bin/odoo scaffold test /mnt/extra-addons
```

The use of /usr/bin/odoo is odd because we always add the database arguments to any command named "odoo", however for the special case of the scaffolding you cannot add more parameters than needed. This should probably fixed upstream, else i'd make a dirty hack in the entrypoint.

Regards
