### ISSUE TITLE
/var/lib/odoo not mountable on OSX with docker-machine

### ISSUE THREAD

**Issue by rikvermeer** [odoo/docker#40]
Docker volume /var/lib/odoo is mountable on OSX but then docker fails to boot the odoo image.

ERP_1    | Traceback (most recent call last):
ERP_1    |   File "/usr/bin/openerp-server", line 5, in <module>
ERP_1    |     openerp.cli.main()
ERP_1    |   File "/usr/lib/python2.7/dist-packages/openerp/cli/command.py", line 64, in main
ERP_1    |     o.run(args)
ERP_1    |   File "/usr/lib/python2.7/dist-packages/openerp/cli/server.py", line 166, in run
ERP_1    |     main(args)
ERP_1    |   File "/usr/lib/python2.7/dist-packages/openerp/cli/server.py", line 120, in main
ERP_1    |     openerp.tools.config.parse_config(args)
ERP_1    |   File "/usr/lib/python2.7/dist-packages/openerp/tools/config.py", line 308, in parse_config
ERP_1    |     openerp.modules.module.initialize_sys_path()
ERP_1    |   File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 77, in initialize_sys_path
ERP_1    |     dd = tools.config.addons_data_dir
ERP_1    |   File "/usr/lib/python2.7/dist-packages/openerp/tools/config.py", line 557, in addons_data_dir
ERP_1    |     os.makedirs(d, 0700)
ERP_1    |   File "/usr/lib/python2.7/os.py", line 150, in makedirs
ERP_1    |     makedirs(head, mode)
ERP_1    |   File "/usr/lib/python2.7/os.py", line 157, in makedirs
ERP_1    |     mkdir(name, mode)
ERP_1    | OSError: [Errno 13] Permission denied: '/var/lib/odoo/addons'

**Comment by jaredkipe** [comment]
This is fairly common it would seem when using Virtualbox as the provider when the running application needs different permissions (e.g. mounting a data partition for postgres)

**Comment by rikvermeer** [comment]
I just thought it should be clear that osx users shouldn’t mount certain volumes.

Besides that, Odoo is the first application that I encounter in which this is a problem for me.
All the answers I find are intrusive or un-elegant and maybe someone here can tell me 
how should I use scaffolding and work from my host system on the files?

Would you use nfs, git or another volume driver?

**Comment by jaredkipe** [comment]
Probably.. using a NFS share (which is what I do with Vagrant all the time) does give better file permission control and performance over the built in Virtualbox shares.  I'm not sure if it would be good enough given the way docker then re-shares into the containers, but its probably a better place to go than virtualbox shares.

There are however many downsides to NFS shares over Virtualbox ones.  Coordination with the host os (OSX) to make the share and scope it to the IP address of the docker host VM.  Coordination in the guest (docker VM) to mount the share.  Vagrant does all this and is fairly good at it.

The problem is that this is platform specific.  Only the Mac (or Linux and Mac) version of docker-machine could/would be responsible for all the wiring on VM creation and startup.

**Comment by jaredkipe** [comment]
Ok, it does work via NFS shares.

Odoo might be ok, but for the Postgres data volume I did have to -maproot=root because of what it tries to do to the mounted files.

Basically:
In OSX 
```
#sudo nano /etc/exports 
(add a line with `"/Users" -alldirs -rw -maproot=root` -- I'm aware this is super dangerous, you should scope it to the subnet that docker is running on (not the 192. but the 10.))
#sudo nfsd restart #may not be needed
```

Use docker-machine to ssh into the VM:
```
#sudo umount /Users
#sudo /usr/local/etc/init.d/nfs-client start
#sudo mount $YOUR_MAC_IP:/Users /Users -o rw,async,noatime,rsize=32768,wsize=32768,proto=tcp,actimeo=1,nolock,vers=3
```

Then you can simply put that above VM part into a bash script that you can locate at `/var/lib/boot2docker/bootlocal.sh` (mine didn't have the file, but if you create it and throw a normal `#!/bin/bash` at the top (and chmod a+x the file) it will run on boot of the VM.

**Comment by jaredkipe** [comment]
This should be closed.

Also FWIW, I've taken to running a Vagrant CoreOS box that I hook docker-machine up to for dev purposes.  Vagrant does a better job of consistently configuring the box in the way I would like it to be configured that boot2docker.
