### ISSUE TITLE
[8.0] Can't set Postgres user

### ISSUE THREAD

**Issue by devent** [odoo/docker#66]
Hello, I tried the Odoo 8 docker image, but I can't set the Odoo database user.
I run the docker container with

```
-e DB_PORT_5432_TCP_ADDR="postgres_9_4.weave.local" \
-e DB_PORT_5432_TCP_PORT="5432" \
-e DB_ENV_POSTGRES_USER="odoo8" \
-e DB_ENV_POSTGRES_PASSWORD="xxx" \
```

But the error is

```
OperationalError: FATAL:  password authentication failed for user "odoo"
```

That is weird because I put extra an echo command in the Docker image so that I can see the exported env. variables:

```
(echo "Export host: $PGHOST; port: $PGPORT; user: $PGUSER")
Export host: postgres_9_4.weave.local; port: 5432; user: odoo8
```

If I create the user "odoo" in Postgres, Odoo works. But of course I rather have the option to set the Odoo database user name.

I use the latest Odoo 8.0 build. odoo_8.0.20160727_all.deb

**Comment by jaredkipe** [comment]
Thats interesting, because it isn't using the 'default' user of 'postgres' as defined in /entrypoint.sh so something deeper is going on.  Since the user that odoo runs as is 'odoo' I have a suspicion that it is trying, in fact, to connect to a local socket or something instead of using the TCP connection parameters.
Can you exec in and try to ping that db port?  Maybe `psql -U odoo9 -h postgres_9_4.weave.local`

**Comment by sle-odoo** [comment]
What do you have in /etc/odoo/openerp-server.conf?
