### ISSUE TITLE
lstat entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by thangdc030** [odoo/docker#68]
Step 7 : COPY ./entrypoint.sh /
lstat entrypoint.sh: no such file or directory

I built using https://github.com/odoo/docker/blob/master/8.0/Dockerfile and that error occured.

**Comment by jaredkipe** [comment]
Did you checkout/clone the repository? entrypoint.sh is clearly in the repo in the dame file as the Dockerfile.

**Comment by sle-odoo** [comment]
Closing as @jaredkipe said the file is there and the builds are successful.

**Comment by jordi-starlab** [comment]
Registered just to say this ain't working.

Docker for Odoo v8 (which I really need) doesn't work, gives this error message; tried it on a clean linux and a clean-ish Windows 10.

**Comment by thomas15v** [comment]
@jordi-starlab Can't you just inherit the image like this?:

```DockerFile
FROM odoo:8

USER root

# modify stuff
RUN apt update && apt install awesomeness 

USER odoo

```

**Comment by jordi-starlab** [comment]
Tried it.
Wrote "USER root" on line 25 and then "USER odoo" on 40 (before the chown).

Line 38 still fails with the "entrypoint.sh: no such file or directory"

I'm doing some investigating (running -i and --rm to start the instance and try to find what it does) because I **need** this to work in the next 48h so any piece of advice or crazy idea is welcomed :)

**Comment by thomas15v** [comment]
This works fine for me tho:
![image](https://user-images.githubusercontent.com/2163941/30900562-c2bc5f30-a364-11e7-8173-1a55decbf2f4.png)

**Comment by jordi-starlab** [comment]
I could install (and have running) a postgresql docker, but I'm new at this and maybe I'm not getting the steps right.
You download the dockerfile (Odoo 8.0 Dockerfile), put it onto a new folder (just for the sake of it, really) and then do:
 sudo docker build -t eg_odoo .
Which will inevitably finish with:
 ---> 112d65a65b1e
Step 7/16 : COPY ./entrypoint.sh /
COPY failed: stat /var/lib/docker/tmp/docker-builder720677126/entrypoint.sh: no such file or directory

I've done it on three different machines already.
More info, since the image is called 112d65a65b1e then I do this "docker run --rm -it 112d65a65b1e sh" to connect to it; if I do a "find / -name 'entrypoint.sh' " nothing comes out.

I'm currently following a clean odoo installation so I can find this entrypoint and fix it (I really need it on a Docker for testing)

**Comment by jordi-starlab** [comment]
Quick note, it appears that the openerp-server.conf was somehow already on /etc/odoo/ (maybe it did copied it on a previous attempt?) and commenting lines 38,39 and 40 lets you finish the build.

I'll check if it works and update accordingly ^_^

**Comment by thomas15v** [comment]
> You download the dockerfile (Odoo 8.0 Dockerfile)

Not at all the odoo 8 image is stored on the docker hub repository. Docker will download that by itself. 
Also I highly advice you use something like [docker-compose](https://github.com/thomas15v/odoo_docker/blob/master/docker_compose_simple/docker-compose.yml) to manage your images/containers.

If you're still into building odoo yourself (what I do not advice, unless you have a specific reason to do so). Your missing entrypoint.sh next to your Dockerfile. You need to have the following files before building: 

- Dockerfile
- openerp-server.conf
- entrypoint.sh (do chmod +x on this file)
