### ISSUE TITLE
[10.0] python-xlrd needed for xls import

### ISSUE THREAD

**Issue by mgielissen** [odoo/docker#77]
Python module python-xlrd is needed for importing xls files

**Comment by Kazebayashi** [comment]
Hi
I just added `&& pip install xlrd ` after `&& pip install psycogreen==1.0 \`  in the dockerfile and it worked fine for me.
Note that I had to add also `RUN chmod u+x /entrypoint.sh` after `COPY ./entrypoint.sh /` otherwise I had an error message saying permission denied for entrypoint.sh.

**Comment by sle-odoo** [comment]
That's strange, i can't see any occurence of the "xlrd" python library in the upstream code. Where does this triggers an issue?

**Comment by mgielissen** [comment]
I got the issue on importing a xls file.

**Comment by Kazebayashi** [comment]
The issue happen when you want to import a xls file instead of a csv file (contacts, or products).

Python-xlrd is not included in the official repository.
So you need to build your own image of odoo using a modified dockerfile, on which you add xlrd installation.

Sorry, maybe it's obvious for you guys how to do that, but I'm beginner in linux and docker and I was happy that a friend of mine explained me how to do, so I write it down here. It may be usefull for someone:
- [ ] Connect via sftp to your server
- [ ] Create a folder called "odoo" in "home/username"
- [ ] Unzip this folder on your computer and put the 3 files on the odoo folder you created, via sftp.
[odoo-xlrd.zip](https://github.com/odoo/docker/files/604731/odoo-xlrd.zip)
- [ ] Then connect to your server via ssh
- [ ] Go in the odoo folder : `cd /home/username/odoo`
- [ ] Build your image (we will call it "odoo/xlrd" : `docker build -t odoo/xlrd .`
- [ ] Wait...
- [ ] Then when finnished, you can run your image: `docker run -p 8069:8069 --name odoo-xlrd --link db:db -d -t odoo/xlrd` (after you previously ran postgres of course).

**Comment by sle-odoo** [comment]
this'll be handled upstream in https://github.com/odoo/odoo/pull/14330

thank you
