### ISSUE TITLE
[10.0] Forced default Database parameters

### ISSUE THREAD

**Issue by almeidapaulopt** [odoo/docker#80]
Runing a new Docker without specify the database parameter, odoo starts with
 "--db_user odoo --db_password odoo --db_host db --db_port 5432" ignoring variables in config file.

**Comment by sle-odoo** [comment]
you are right. we should check first the if they are any entries for the database credentials in the config file and use them accordingly.

**Comment by sle-odoo** [comment]
but actually it's not clear which connection parameter should be used, the one you pass as argument, the one set in the environment variable or the one set in your config file?

let's wait until monday before changing this one

**Comment by thucnc** [comment]
Hi,
I don't know how to set the pg info. May you give me any guide or example ? Thanks

**Comment by LeartS** [comment]
Yeah, commit https://github.com/odoo/docker/commit/a3d207f2d49c3a0eb0e959fbf2cb33909c382a3f completely broke db configuration options, it's kinda ridiculous.

**Comment by sle-odoo** [comment]
@LeartS it workarounds upstream issues with odoo and pg* env variables by not using them. Their use was an error from the start but the fix is backward compatible with the way we start odoo as suggested in the documentation.

There are two broken things i am aware until now: skip of the the db entries in the configuration file and odoo commands like shell and deploy that are implemented in a terrible way and break if some argument are not exactly at their expected places. Also custom docker-compose file may break because they used the pg* variables but we won't fix that, instead we wil merge https://github.com/docker-library/docs/pull/720#issuecomment-259813852 and then.. we won't break them.

A fix will come in the next few days but sadly my to do list is full of entries with an high priority... I'm sorry for the delay. If you have some other suggestion for fixes and improvements please tell me and i'll be happy to work on them.

**Comment by anassahmed** [comment]
This has broken our client deployed containers!

We don't use a docker legacy linking system, we use the host PostgreSQL which was configured using the config file. Now, I had to use the command line options to launch the container.

**Comment by sle-odoo** [comment]
@anassahmed you're talking about the odoo configuration file right? this will be fixed soon.

@LeartS @anassahmed i will ping you guys on the next PR so that you'll confirm your issues are fixed with it.
