### ISSUE TITLE
Update to more recent revision

### ISSUE THREAD

**Issue by LeartS** [odoo/docker#89]
It is possible to update the docker revision to one of the recent ones? In the currently included one (20161123) there are some big bugs, like https://github.com/odoo/odoo/pull/14457 which makes timesheet unusable (ValueError as soon as you try open a sheet with more than 1 value)

**Comment by sle-odoo** [comment]
i'll do it soon. I'll do it sooner if we had some kind of automated build in this repo so i don't have to build the three images and test them locally before pushing :)

**Comment by PieterPaulussen** [comment]
@LeartS You could always build the image from the Dockerfile? @sle-odoo  Doesn't the docker file get the most current Debian installation? 
Another option would be to create your own Dockerfile and add an Odoo and custom folder mounted to the image. That way the image could be updated regularly.

**Comment by taliaga** [comment]
@LeartS As a temporary fix you can edit the [ODOO_RELEASE variable](https://github.com/odoo/docker/blob/master/10.0/Dockerfile#L26) of the Dockerfile to something more recent [check here](http://nightly.odoo.com/9.0/nightly/deb/), e.g 20161219, and comment out [this line](https://github.com/odoo/docker/blob/master/10.0/Dockerfile#L29). Then build locally with a simple docker build.

@PieterPaulussen Noup, as of today, it's hardcoded to a specific version of the .deb (ODOO_RELEASE) and apparently it's been manually updated.

@sle-odoo Correct me if I'm wrong but If the nightly cron job published the sha1sum of the .deb package then the Dockerfile could be changed to use "latest" and fetch the sha1sum to check against directly from the repository. Do you know which job is publishing those builds?

**Comment by steenzout** [comment]
@sle-odoo I've made a PR #93 which should make it easier to automate this process.

let me know if you are interested.

**Comment by lcrea** [comment]
Hi @LeartS ,
if you're interested, I've recently made few changes in a fork of this repo. Check it out:
[https://github.com/lcrea/odoo-docker](https://github.com/lcrea/odoo-docker)

In particular, I set the ODOO_RELEASE variable (in each version) to point to the `latest` symlink file inside the nightly build folders.
Obviously you have to manually recompile the image, but you will always get the latest version and this little issue can be easily solved with a cron task 😉 

The only advise is: because the Dockerfile remains the same, it's important to compile the image **without the cache**, like this:

`docker build --no-cache -t my/odoo:10 .`

It's still a work in progress for me (I actually would like to develop an alpine version and trying to sync the repo with a docker registry), but it already works 😊 

I hope could be helpful.
